# Generated by Django 4.2.3 on 2023-07-19 14:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Partner', max_length=250)),
                ('logo', models.ImageField(upload_to='partner_logos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states_covered', models.SmallIntegerField()),
                ('schools', models.SmallIntegerField()),
                ('teachers_trained', models.SmallIntegerField()),
                ('students_impacted', models.SmallIntegerField()),
                ('employment_generated', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('students_impacted', models.SmallIntegerField(blank=True, null=True)),
                ('educators', models.SmallIntegerField(blank=True, null=True)),
                ('country_reached', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('impact', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(help_text='primary image', upload_to='project_image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='project_image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='project_image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='project_image')),
                ('past', models.BooleanField()),
                ('upcoming', models.BooleanField()),
                ('community', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ManyToManyField(blank=True, to='LearnHillApp.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_profile_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='blog_cards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnHillApp.profile')),
                ('category', models.ManyToManyField(to='LearnHillApp.category')),
            ],
        ),
    ]
