# Generated by Django 4.2.3 on 2023-07-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Partner', max_length=250)),
                ('logo', models.ImageField(upload_to='partner_logos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states_covered', models.SmallIntegerField()),
                ('schools', models.SmallIntegerField()),
                ('teachers_trained', models.SmallIntegerField()),
                ('students_impacted', models.SmallIntegerField()),
                ('employment_generated', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='project_image/')),
                ('image2', models.ImageField(upload_to='project_image/')),
                ('image3', models.ImageField(upload_to='project_image/')),
                ('image4', models.ImageField(upload_to='project_image/')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_year', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('students_impacted', models.SmallIntegerField()),
                ('school_reached', models.SmallIntegerField()),
                ('action', models.TextField()),
                ('impact', models.TextField()),
                ('Past', models.BooleanField()),
                ('Upcoming', models.BooleanField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnHillApp.partner')),
            ],
        ),
    ]
