# Generated by Django 4.2.3 on 2023-08-15 13:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnHillApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='subheading',
        ),
        migrations.AddField(
            model_name='program',
            name='Statistics',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LearnHillApp.statistic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='action',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='objective',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
