# Generated by Django 4.2.3 on 2023-07-16 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnHillApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_year', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('students_impacted', models.SmallIntegerField()),
                ('school_reached', models.SmallIntegerField()),
                ('action', models.TextField()),
                ('impact', models.TextField()),
                ('Past', models.BooleanField()),
                ('Upcoming', models.BooleanField()),
                ('image1', models.ImageField(upload_to='project_image/')),
                ('image2', models.ImageField(upload_to='project_image/')),
                ('image3', models.ImageField(upload_to='project_image/')),
                ('image4', models.ImageField(upload_to='project_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnHillApp.partner')),
            ],
        ),
        migrations.DeleteModel(
            name='programs',
        ),
    ]
