# Generated by Django 4.2.3 on 2023-09-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnHillApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('org_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
