# Generated by Django 4.2.3 on 2023-07-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnHillApp', '0002_program_delete_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image1',
            field=models.ImageField(upload_to='project_image'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image2',
            field=models.ImageField(upload_to='project_image'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image3',
            field=models.ImageField(upload_to='project_image'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image4',
            field=models.ImageField(upload_to='project_image'),
        ),
    ]
