# Generated by Django 4.2.3 on 2023-08-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnHillApp', '0002_remove_program_subheading_program_statistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='name',
            field=models.CharField(default='', help_text='name of page stats belong to', max_length=255),
            preserve_default=False,
        ),
    ]
