# Generated by Django 4.2.3 on 2023-08-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnHillApp', '0003_statistic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='name',
        ),
    ]
