# Generated by Django 4.2.3 on 2023-08-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnHillApp', '0004_remove_statistic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='country_reached',
            new_name='district_participated',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='educators',
            new_name='schools_participated',
        ),
        migrations.RemoveField(
            model_name='program',
            name='Statistics',
        ),
        migrations.RemoveField(
            model_name='program',
            name='location',
        ),
        migrations.AddField(
            model_name='program',
            name='state',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='teachers_trained',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
