# Generated by Django 4.2.3 on 2023-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnHillApp', '0005_rename_country_reached_program_district_participated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='district_participated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='image1',
            field=models.ImageField(help_text='primary image: PUT a Square Image Here', upload_to='project_image'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image4',
            field=models.ImageField(blank=True, help_text='Extra Image to Adjust Past Program Page', null=True, upload_to='project_image'),
        ),
        migrations.AlterField(
            model_name='program',
            name='schools_participated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='students_impacted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='teachers_trained',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
