# Generated by Django 4.2.3 on 2023-08-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnHillApp', '0006_alter_program_district_participated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='students_impacted',
            new_name='students_trained',
        ),
    ]
